# Generated by Django 4.2.4 on 2023-08-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_alter_subscriber_email'),
        ('emails', '0002_alter_scheduledemail_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledemail',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='scheduledemail',
            name='subscribers',
            field=models.ManyToManyField(to='subscribers.subscriber'),
        ),
    ]
