# Generated by Django 4.2.4 on 2023-08-30 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_alter_scheduledemail_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledemail',
            old_name='subscribers',
            new_name='subs',
        ),
    ]
