# Generated by Django 4.2.4 on 2023-08-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_alter_subscriber_email'),
        ('emails', '0007_alter_scheduledemail_subs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledemail',
            name='subs',
            field=models.ManyToManyField(blank=True, to='subscribers.subscriber'),
        ),
    ]
