# Generated by Django 4.2.4 on 2023-09-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0004_remove_subscriber_name'),
        ('emails', '0008_alter_scheduledemail_subs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledemail',
            name='subs',
            field=models.ManyToManyField(to='subscribers.subscriber'),
        ),
    ]
