# Generated by Django 4.2.4 on 2023-09-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0009_alter_scheduledemail_subs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledemail',
            name='subs',
        ),
    ]
