# Generated by Django 4.2.4 on 2023-08-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='date_subscribed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
